import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../component/header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>グルメ検索サイト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header/>
      </main>
      
    </div>
  );
}
