import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../component/header';
import Grid from '@mui/material/Grid';
import { styled } from '@mui/material/styles';
import Paper from '@mui/material/Paper';
import Box from '@mui/material/Box';
import { Card, CardMedia, Typography } from '@mui/material';
import Link from 'next/link';

export default function Home() {
  const Item = styled(Paper)(({ theme }) => ({
    backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
    ...theme.typography.body2,
    padding: theme.spacing(1),
    textAlign: 'center',
    color: theme.palette.text.secondary,
  }));

  return (
    <div>
      <Head>
        <title>グルメ検索サイト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Box sx={{ pt: 3, px: 8 }}>
          <Grid container spacing={4}>
            <Grid item xs={3} sx={{ maxWidth: 300 }}>
              <Link href="https://www.hotpepper.jp/SA98/" rel="noopener noreferrer" target="_blank">
                <Card sx={{ mb: 1, boxShadow: 0, borderRadius: 2, width: 'auto' }}>
                  <CardMedia
                    className={styles.card}
                    style={{
                      background: 'gray',
                      padding: 0,
                      margin: 0,
                      marginBottom: 8,
                      maxWidth: '100%',
                      display: 'block',
                    }}
                    component="img"
                    image="https://imgfp.hotp.jp/IMGH/73/49/P035907349/P035907349_238.jpg"
                  />
                  <Box sx={{ display: 'flex' }}>
                    <Typography sx={{ fontWeight: 'bold' }}>ぱいかじ</Typography>
                    <Typography sx={{ ml: 'auto', fontWeight: 'bold' }}>300m</Typography>
                  </Box>
                  <Typography>居酒屋</Typography>
                  <Typography>10:00～21:00</Typography>
                </Card>
              </Link>
            </Grid>
          </Grid>
        </Box>
      </main>
    </div>
  );
}
