import { useEffect, useState } from 'react';
import Head from 'next/head';
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import { Card, CardMedia, Typography } from '@mui/material';
import Link from 'next/link';
import Header from '../component/header';
import styles from '../styles/Home.module.css';
import {fetchGourmets} from '../lib/fetchHelper'

export default function Home({ firstViewGourmets }) {
  const [gourmets, setGourmets] = useState([]);

  useEffect(() => {
    setGourmets(firstViewGourmets);
  }, [firstViewGourmets]);

  return (
    <div>
      <Head>
        <title>グルメ検索サイト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Box sx={{ pt: 3, px: 7 }} >
          <Grid container spacing={4}>
            {gourmets.map((gourmet) => {
              return (
                <Grid item xs={6} sm={4} md={3} sx={{ maxWidth: 300 }} key={gourmet.id}>
                  <Link href={`${gourmet.urls.pc}`} rel="noopener noreferrer" target="_blank">
                    <Card sx={{ mb: 1, boxShadow: 0, borderRadius: 0, width: 'auto' }}>
                      <CardMedia
                        className={styles.card}
                        style={{
                          background: `url('${gourmet.photo.pc.l}') no-repeat center`,
                          backgroundSize: 'cover',
                        }}
                        component="img"
                      />
                      <Box sx={{ display: 'flex' }}>
                        <Typography sx={{ fontSize: '15px', fontWeight: 'bold' }}>{gourmet.name}</Typography>
                        <Typography sx={{ ml: 'auto', fontWeight: 'bold' }}>000m</Typography>
                      </Box>
                      <Box sx={{ color: 'gray' }}>
                        <Typography sx={{ fontSize: '15px', lineHeight: '1.2' }}>{gourmet.genre.name}</Typography>
                        <details>
                          <summary style={{ fontSize: '15px' }}>営業時間</summary>
                          <Typography sx={{ fontSize: '15px' }}>{gourmet.open}</Typography>
                        </details>
                      </Box>
                    </Card>
                  </Link>
                </Grid>
              );
            })}
          </Grid>
        </Box>
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const gourmets = await fetchGourmets();

  return {
    props: {
      firstViewGourmets: gourmets,
    },
  };
};
